export const ADMIN_PRODUCT_LIST_REQUEST = "ADMIN_PRODUCT_LIST_REQUEST";
export const ADMIN_PRODUCT_LIST_SUCCESS = "ADMIN_PRODUCT_LIST_SUCCESS";
export const ADMIN_PRODUCT_LIST_FAIL = "ADMIN_PRODUCT_LIST_FAIL";

export const ADMIN_PRODUCT_DETAILS_REQUEST = "ADMIN_PRODUCT_DETAILS_REQUEST";
export const ADMIN_PRODUCT_DETAILS_SUCCESS = "ADMIN_PRODUCT_DETAILS_SUCCESS";
export const ADMIN_PRODUCT_DETAILS_FAIL = "ADMIN_PRODUCT_DETAILS_FAIL";

export const ADMIN_PRODUCT_SAVE_REQUEST = "ADMIN_PRODUCT_SAVE_REQUEST";
export const ADMIN_PRODUCT_SAVE_SUCCESS = "ADMIN_PRODUCT_SAVE_SUCCESS";
export const ADMIN_PRODUCT_SAVE_FAIL = "ADMIN_PRODUCT_SAVE_FAIL";

export const ADMIN_PRODUCT_DELETE_REQUEST = "ADMIN_PRODUCT_DELETE_REQUEST";
export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS";
export const ADMIN_PRODUCT_DELETE_FAIL = "ADMIN_PRODUCT_DELETE_FAIL";
